AWSTemplateFormatVersion: '2010-09-09'
Description: Various preparations for environment construction.
Parameters:
  AppEnv:
    Description: Specify from parent stack
    Type: String
  AppProjectName:
    Description: Specify from parent stack
    Type: String
Mappings:
  RegionMap:
    # AWS account IDs to grant Elastic Load Balancing access to the S3 bucket
    # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-logging-bucket-permissions
    'us-east-1':
      AccountId: '127311923021'
    'us-east-2':
      AccountId: '033677994240'
    'us-west-1':
      AccountId: '027434742980'
    'us-west-2':
      AccountId: '797873946194'
    'ca-central-1':
      AccountId: '985666609251'
    'eu-central-1':
      AccountId: '054676820928'
    'eu-west-1':
      AccountId: '156460612806'
    'eu-west-2':
      AccountId: '652711504416'
    'eu-west-3':
      AccountId: '009996457667'
    'ap-northeast-1':
      AccountId: '582318560864'
    'ap-northeast-2':
      AccountId: '600734575887'
    'ap-southeast-1':
      AccountId: '114774131450'
    'ap-southeast-2':
      AccountId: '783225319266'
    'ap-south-1':
      AccountId: '718504428378'
    'sa-east-1':
      AccountId: '507241528517'
    'us-gov-west-1':
      AccountId: '048591011584'
    'cn-north-1':
      AccountId: '638102146993'
    'cn-northwest-1':
      AccountId: '037604701340'
Resources:
  S3ALBLogBucket:
    #DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppEnv}-elb-logs-${AWS::AccountId}'
      LifecycleConfiguration:
        Rules:
        - Id: GlacierRule
          Status: Enabled
          Transitions:
            - StorageClass: GLACIER
              TransitionInDays: 365
          ExpirationInDays: 545
  S3ALBLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'S3ALBLogBucket'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Bucket Policy - ALB Logging
            Effect: Allow
            Principal:
              AWS:
                - !FindInMap [RegionMap, !Ref 'AWS::Region', AccountId]
            Action:
              - s3:PutObject
            Resource:
              - !Sub 'arn:aws:s3:::${S3ALBLogBucket}/${AppEnv}-${AppProjectName}-xxx/AWSLogs/${AWS::AccountId}/*'
              - !Sub 'arn:aws:s3:::${S3ALBLogBucket}/${AppEnv}-${AppProjectName}-xxx/AWSLogs/${AWS::AccountId}/*'
Outputs:
  ALBLogBucket:
    Description: S3 bucket name 
    Value: !Ref 'S3ALBLogBucket'
    Export:
      Name: !Sub '${AWS::StackName}-ALBLogBucket'
